package SF548;

public class characters {
    public static characters convert(TC335.characters oldcharacter) {
        characters newcharacter = new characters();
        newcharacter.guid = oldcharacter.guid;
        newcharacter.account = oldcharacter.account;
        newcharacter.name = oldcharacter.name;
        newcharacter.race = oldcharacter.race;
        newcharacter.i_class = oldcharacter.i_class;
        newcharacter.gender = oldcharacter.gender;
        newcharacter.level = oldcharacter.level;
        newcharacter.xp = oldcharacter.xp;
        newcharacter.money = oldcharacter.money;
        newcharacter.playerflags = oldcharacter.playerflags;
        newcharacter.pos_x = oldcharacter.pos_x;
        newcharacter.pos_y = oldcharacter.pos_y;
        newcharacter.pos_z = oldcharacter.pos_z;
        newcharacter.map = oldcharacter.map;
        newcharacter.instance_id = oldcharacter.instance_id;
        newcharacter.orientation = oldcharacter.orientation;
        newcharacter.taximask = oldcharacter.taximask;
        newcharacter.online = oldcharacter.online;
        newcharacter.cinematic = oldcharacter.cinematic;
        newcharacter.totaltime = oldcharacter.totaltime;
        newcharacter.leveltime = oldcharacter.leveltime;
        newcharacter.logout_time = oldcharacter.logout_time;
        newcharacter.is_logout_resting = oldcharacter.is_logout_resting;
        newcharacter.rest_bonus = oldcharacter.rest_bonus;
        newcharacter.resettalents_cost = oldcharacter.resettalents_cost;
        newcharacter.resettalents_time = oldcharacter.resettalents_time;
        newcharacter.trans_x = oldcharacter.trans_x;
        newcharacter.trans_y = oldcharacter.trans_y;
        newcharacter.trans_z = oldcharacter.trans_z;
        newcharacter.trans_o = oldcharacter.trans_o;
        newcharacter.transguid = oldcharacter.transguid;
        newcharacter.extra_flags = oldcharacter.extra_flags;
        //newcharacter.stable_slots = oldcharacter.stable_slots;
        newcharacter.at_login = oldcharacter.at_login;
        newcharacter.zone = oldcharacter.zone;
        newcharacter.death_expire_time = oldcharacter.death_expire_time;
        newcharacter.taxi_path = oldcharacter.taxi_path;
        newcharacter.totalkills = oldcharacter.totalkills;
        newcharacter.todaykills = oldcharacter.todaykills;
        newcharacter.yesterdaykills = oldcharacter.yesterdaykills;
        newcharacter.chosentitle = oldcharacter.chosentitle;
        newcharacter.watchedfaction = oldcharacter.watchedfaction;
        newcharacter.drunk = oldcharacter.drunk;
        newcharacter.health = oldcharacter.health;
        newcharacter.power1 = oldcharacter.power1;
        newcharacter.power2 = oldcharacter.power2;
        newcharacter.power3 = oldcharacter.power3;
        newcharacter.power4 = oldcharacter.power4;
        newcharacter.power5 = oldcharacter.power5;
        newcharacter.latency = oldcharacter.latency;
        newcharacter.speccount = oldcharacter.talentgroupscount;
        newcharacter.activespec = oldcharacter.activetalentgroup;
        newcharacter.exploredzones = oldcharacter.exploredzones;
        newcharacter.equipmentcache = oldcharacter.equipmentcache;
        //newcharacter.knowntitles = oldcharacter.knowntitles;
        newcharacter.actionbars = oldcharacter.actionbars;
        newcharacter.grantablelevels = oldcharacter.grantablelevels;
        newcharacter.deleteinfos_acount = oldcharacter.deleteinfos_acount;
        newcharacter.deleteinfos_name = oldcharacter.deleteinfos_name;
        newcharacter.deletedate = oldcharacter.deletedate;

        newcharacter.playerbytes = oldcharacter.skin * 0x1000000 + oldcharacter.face * 0x10000 + oldcharacter.hairstyle * 0x100 + oldcharacter.haircolor;
        newcharacter.playerbytes2 = oldcharacter.facialstyle * 0x1000000 + oldcharacter.bankslots * 0x10000 + oldcharacter.reststate * 0x100 + oldcharacter.reststate;

        return newcharacter;
    }

    characters() {
        slot = 0;
//        dungeondifficulty = 1;
//        raiddifficulty = 14;
//        talentTree = "'0 0'";
//        lfgbonusfaction = 0;
        instance_mode_mask = 0;
        resetspecialization_cost = 0;
        resetspecialization_time = 0;
        specialization1 = 0;
        specialization2 = 0;
    };

    int guid;
    int account;
    String name;

    int slot;

    int race;
    int i_class;
    int gender;
    int level;
    int xp;
    int money;

    long playerbytes;
    long playerbytes2;

    int playerflags;
    double pos_x;
    double pos_y;
    double pos_z;
    int map;
    int instance_id;

    int instance_mode_mask;
    double orientation;
    String taximask;
    int online;
    int cinematic;
    int totaltime;
    int leveltime;
    int logout_time;
    int is_logout_resting;
    double rest_bonus;
    int resettalents_cost;
    int resettalents_time;

    int resetspecialization_cost;
    int resetspecialization_time;

    double trans_x;
    double trans_y;
    double trans_z;
    double trans_o;
    int transguid;
    int extra_flags;
    int at_login;
    int zone;
    int death_expire_time;
    String taxi_path;

    int totalkills;
    int todaykills;
    int yesterdaykills;
    int chosentitle;
    //int knowncurrencies;
    long watchedfaction;

    int drunk;
    int health;
    int power1;
    int power2;
    int power3;
    int power4;
    int power5;

    int latency;
    int speccount;
    int activespec;
    int specialization1;
    int specialization2;

    String exploredzones;
    String equipmentcache;

    int actionbars;
    int grantablelevels;
    String deleteinfos_acount;
    String deleteinfos_name;
    String deletedate;

    public String to_sql() {
        String sql = "INSERT INTO `characters` VALUES (";
        sql += String.valueOf(guid);
        sql += ", ";
        sql += String.valueOf(account);
        sql += ", ";
        sql += name;
        sql += ", ";
        sql += String.valueOf(slot);
        sql += ", ";
        sql += String.valueOf(race);
        sql += ", ";
        sql += String.valueOf(i_class);
        sql += ", ";
        sql += String.valueOf(gender);
        sql += ", ";
        sql += String.valueOf(level);
        sql += ", ";
        sql += String.valueOf(xp);
        sql += ", ";
        sql += String.valueOf(money);
        sql += ", ";
        sql += String.valueOf(playerbytes);
        sql += ", ";
        sql += String.valueOf(playerbytes2);
        sql += ", ";
        sql += String.valueOf(playerflags);
        sql += ", ";
        sql += String.valueOf(pos_x);
        sql += ", ";
        sql += String.valueOf(pos_y);
        sql += ", ";
        sql += String.valueOf(pos_z);
        sql += ", ";
        sql += String.valueOf(map);
        sql += ", ";
        sql += String.valueOf(instance_id);
        sql += ", ";
//        sql += String.valueOf(dungeondifficulty);
//        sql += ", ";
//        sql += String.valueOf(raiddifficulty);
//        sql += ", ";
        sql += String.valueOf(instance_mode_mask);
        sql += ", ";
        sql += String.valueOf(orientation);
        sql += ", ";
        sql += taximask;
        sql += ", ";
        sql += String.valueOf(online);
        sql += ", ";
        sql += String.valueOf(cinematic);
        sql += ", ";
        sql += String.valueOf(totaltime);
        sql += ", ";
        sql += String.valueOf(leveltime);
        sql += ", ";
        sql += String.valueOf(logout_time);
        sql += ", ";
        sql += String.valueOf(is_logout_resting);
        sql += ", ";
        sql += String.valueOf(rest_bonus);
        sql += ", ";
        sql += String.valueOf(resettalents_cost);
        sql += ", ";
        sql += String.valueOf(resettalents_time);
        sql += ", ";
        sql += String.valueOf(resetspecialization_cost);
        sql += ", ";
        sql += String.valueOf(resetspecialization_time);
        sql += ", ";
//        sql += talentTree;
//        sql += ", ";
        sql += String.valueOf(trans_x);
        sql += ", ";
        sql += String.valueOf(trans_y);
        sql += ", ";
        sql += String.valueOf(trans_z);
        sql += ", ";
        sql += String.valueOf(trans_o);
        sql += ", ";
        sql += String.valueOf(transguid);
        sql += ", ";
        sql += String.valueOf(extra_flags);
        sql += ", ";
//        sql += String.valueOf(stable_slots);
//        sql += ", ";
        sql += String.valueOf(at_login);
        sql += ", ";
        sql += String.valueOf(zone);
        sql += ", ";
        sql += String.valueOf(death_expire_time);
        sql += ", ";
        sql += taxi_path;
        sql += ", ";
        sql += String.valueOf(totalkills);
        sql += ", ";
        sql += String.valueOf(todaykills);
        sql += ", ";
        sql += String.valueOf(yesterdaykills);
        sql += ", ";
        sql += String.valueOf(chosentitle);
        sql += ", ";
        sql += String.valueOf(watchedfaction);
        sql += ", ";
//        sql += String.valueOf(lfgbonusfaction);
//        sql += ", ";
        sql += String.valueOf(drunk);
        sql += ", ";
        sql += String.valueOf(health);
        sql += ", ";
        sql += String.valueOf(power1);
        sql += ", ";
        sql += String.valueOf(power2);
        sql += ", ";
        sql += String.valueOf(power3);
        sql += ", ";
        sql += String.valueOf(power4);
        sql += ", ";
        sql += String.valueOf(power5);
        sql += ", ";
        sql += String.valueOf(latency);
        sql += ", ";
        sql += String.valueOf(speccount);
        sql += ", ";
        sql += String.valueOf(activespec);
        sql += ", ";
        sql += String.valueOf(specialization1);
        sql += ", ";
        sql += String.valueOf(specialization2);
        sql += ", ";
        sql += exploredzones;
        sql += ", ";
        sql += equipmentcache;
        sql += ", ";
//        sql += knowntitles;
//        sql += ", ";
        sql += String.valueOf(actionbars);
        sql += ", ";
        sql += String.valueOf(grantablelevels);
        sql += ", ";
        sql += deleteinfos_acount;
        sql += ", ";
        sql += deleteinfos_name;
        sql += ", ";
        sql += deletedate;
        sql += ");";
        return sql;
    }
}
